### ISSUE TITLE
java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/spi/MessageSourceHandler

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-hibernate-plugin#2]
```
2022-02-07 19:53:37 W/mirai-hibernate-plugin: Exception in Recorder
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callFunction$3.invokeSuspend(JvmMethodListenersInternal.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoClassDefFoundError: xyz/cssxsh/mirai/spi/MessageSourceHandler
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:102)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateConfiguration.scan(MiraiHibernateConfiguration.kt:41)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateConfiguration.load(MiraiHibernateConfiguration.kt:64)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateConfiguration.<init>(MiraiHibernateConfiguration.kt:27)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateConfiguration.<init>(MiraiHibernateConfiguration.kt:22)
        at xyz.cssxsh.mirai.plugin.MiraiSessionCache.get(MiraiSessionCache.kt:24)
        at xyz.cssxsh.mirai.plugin.MiraiSessionCache.get(MiraiSessionCache.kt:7)
        at xyz.cssxsh.mirai.plugin.MiraiSessionCache.get(MiraiSessionCache.kt:7)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateUtilsKt.getFactory(MiraiHibernateUtils.kt:12)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateUtilsKt.useSession(MiraiHibernateUtils.kt:16)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateUtilsKt.useSession$default(MiraiHibernateUtils.kt:14)
        at xyz.cssxsh.mirai.plugin.MiraiHibernateRecorder.record$mirai_hibernate_plugin(MiraiHibernateRecorder.kt:28)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: xyz.cssxsh.mirai.spi.MessageSourceHandler
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 39 more


```

**Comment by LaoLittle** [comment]
使用的是`mcl`的自动更新
