### ISSUE TITLE
HikariPool-1 - Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-hibernate-plugin#4]
```
2022-05-28 22:33:44 W/org.hibernate.engine.jdbc.spi.SqlExceptionHelper: SQL Error: 0, SQLState: null
2022-05-28 22:33:44 E/org.hibernate.engine.jdbc.spi.SqlExceptionHelper: HikariPool-1 - Connection is not available, request timed out after 30000ms.
2022-05-28 22:33:44 W/mirai-hibernate-plugin: SQLException in Recorder
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.getConnection(HikariCPConnectionProvider.java:77)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)
        at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)
        at org.hibernate.internal.AbstractSharedSessionContract.beginTransaction(AbstractSharedSessionContract.java:503)
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateUtilsKt.useSession(MiraiHibernateUtils.kt:26)
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateRecorder.merge(MiraiHibernateRecorder.kt:29)
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateRecorder.access$merge(MiraiHibernateRecorder.kt:27)
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateRecorder$record$3.invokeSuspend(MiraiHibernateRecorder.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-05-28 22:33:44 E/main: Exception in coroutine Bot xxxx.MessageSvcSyncerImpl
java.lang.IllegalStateException: timeout syncing friend message history.
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl.syncMessageSvc(MessageSvcSyncer.kt:68)
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl.access$syncMessageSvc(MessageSvcSyncer.kt:35)
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl$syncMessageSvc$1.invokeSuspend(MessageSvcSyncer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by LaoLittle** [comment]
更新后就这样了（）

**Comment by cssxsh** [comment]
> HikariPool-1 - Connection is not available, request timed out after 30000ms.

请求超时
