### ISSUE TITLE
Unable to create requested service 

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-hibernate-plugin#5]
```
2022-05-28 23:09:07 E/pixiv-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.pixiv-helper of pixiv-helper
org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:146)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:746)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt$factory$2.invoke(PixivSqlLoad.kt:39)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt$factory$2.invoke(PixivSqlLoad.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt.getFactory(PixivSqlLoad.kt:38)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.PixivConfigKt$initConfiguration$11.invokeSuspend(PixivConfig.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.connection.C3P0ConnectionProvider] as strategy [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:156)
        at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.initiateService(ConnectionProviderInitiator.java:138)
        at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.initiateService(ConnectionProviderInitiator.java:41)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        ... 33 more
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [org.hibernate.connection.C3P0ConnectionProvider]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:133)
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:152)
        ... 37 more
Caused by: java.lang.ClassNotFoundException: Could not load requested class : org.hibernate.connection.C3P0ConnectionProvider
        at org.hibernate.boot.registry.classloading.internal.AggregatedClassLoader.findClass(AggregatedClassLoader.java:210)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)
        ... 38 more
```

```
2022-05-28 23:09:16 W/pixiv-helper: 消息回复失败
org.hibernate.HibernateException: HHH000469: The ClassLoaderService can not be reused. This instance was stopped already.
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.getAggregatedClassLoader(ClassLoaderServiceImpl.java:288)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.loadJavaServices(ClassLoaderServiceImpl.java:248)
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.applyServiceContributors(StandardServiceRegistryBuilder.java:397)
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.build(StandardServiceRegistryBuilder.java:368)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:744)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt$factory$2.invoke(PixivSqlLoad.kt:39)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt$factory$2.invoke(PixivSqlLoad.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt.getFactory(PixivSqlLoad.kt:38)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt.useSession(PixivSqlLoad.kt:44)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt.useSession$default(PixivSqlLoad.kt:42)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.model.PixivSqlLoadKt.random(PixivSqlLoad.kt:374)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand.randomEroArtWorkInfos(PixivEroCommand.kt:35)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand.access$randomEroArtWorkInfos(PixivEroCommand.kt:12)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand$ero$2.invokeSuspend(PixivEroCommand.kt:71)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand$ero$2.invoke(PixivEroCommand.kt)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand$ero$2.invoke(PixivEroCommand.kt)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.PixivUtilsKt.withHelper(PixivUtils.kt:40)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.PixivUtilsKt.withHelper(PixivUtils.kt:89)
        at pixiv-helper-1.10.0-M3.mirai.jar//xyz.cssxsh.mirai.pixiv.command.PixivEroCommand.ero(PixivEroCommand.kt:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:329)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
> Caused by: java.lang.ClassNotFoundException: Could not load requested class : org.hibernate.connection.C3P0ConnectionProvider

C3P0ConnectionProvider 已不受支持
