### ISSUE TITLE
在mirai 2.12.0中出现`NoClassFoundException`

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-hibernate-plugin#7]
```
2022-07-04 23:33:29 W/mirai-hibernate-plugin: Exception in Recorder
java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/message/OnlineImage
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.entry.FaceRecord$Companion.fromImage(FaceRecord.kt:61)
        at mirai-hibernate-plugin-2.2.3.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateRecorder$record$2.invokeSuspend(MiraiHibernateRecorder.kt:40)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.message.OnlineImage
        ... 8 more
```

**Comment by LaoLittle** [comment]
release 2.3.0
